/****************************************************************************
**
** Copyright (C) 1992-$THISYEAR$ $TROLLTECH$. All rights reserved.
**
** This file is part of $PRODUCT$.
**
** $JAVA_LICENSE$
**
** This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
** WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
**
****************************************************************************/

package com.trolltech.qt;

import com.trolltech.qt.gui.QWidget;

/**
 * Common interface for all classes generated by juic from Designer's .jui
 * files.
 */
public interface QUiForm<T extends QWidget> {

    /**
     * Initializes widgets that are part of the user interface and organizes
     * them into layouts on top of the given widget.
     *
     * @param widget The widget for which the user interface should be created.
     */
    public void setupUi(T widget);

}
