######################################################################
# Automatically generated by qmake (2.00a) Wed Mar 1 11:43:39 2006
######################################################################

QT+=sql
TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
