######################################################################
# Automatically generated by qmake (2.00a) Mon Nov 28 13:32:26 2005
######################################################################

TEMPLATE = app
TARGET = tst_binder

CONFIG += qttest_p4

# Input
SOURCES += tst_binder.cpp

RXXPATH = $$PWD/../../
include($$RXXPATH/rxx.pri)
